language: ruby
rvm:
  - "1.9.2"
  - "1.9.3" 
 - jruby-19mode # JRuby in 1.9 mode
# Disabled for the time being, see https://github.com/dmytro/nagira/issues/9
#  - rbx-19mode
env:
  - RACK_ENV=test
branches:
  only:
    - master
script: bundle exec rspec spec
