language: ruby
rvm:
#  - "1.9.2" ### Gem::InstallError: listen requires Ruby version >= 1.9.3.
  - "1.9.3"
  - "2.0.0"
  # - "2.1.0"
  # - "2.1.1"
  # - "2.1.2"
  # - "2.1.3"
  # - "2.1.4"
  - "2.1.5"
  - "2.2.0"
  - "2.2.1"
#  - jruby-19mode # JRuby in 1.9 mode - Sinatra fails. Disabled on Mar/15'13
# Disabled for the time being, see https://github.com/dmytro/nagira/issues/9
#  - rbx-19mode
env:
  - RACK_ENV=test
branches:
  only:
    - master
script: bundle exec rspec spec
